import { FilasyColumnas } from './filas-columnas';

export const Tablero = () => {

  return (
    <>
    <h1 className='titulo'>Battleship</h1>
      <div className='tablero'>
        <FilasyColumnas
          selda2="1"
          selda3="2"
          selda4="3"
          selda5="4"
          selda6="5"
          selda7="6"
          selda8="7"
          selda9="8"
          selda10="9"
        />
        <FilasyColumnas
          selda1="1"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="2"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="3"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="4"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="5"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="6"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="7"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="8"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
        <FilasyColumnas
          selda1="9"
          selda2="2"
          selda3="3"
          selda4="4"
          selda5="5"
          selda6="6"
          selda7="7"
          selda8="8"
          selda9="9"
          selda10="10"
        />
      </div>
    </>
  )
}